// <auto-generated />
using System;
using Elev8WebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Elev8WebApp.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Elev8WebApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateOfEmployment")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_employment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Elev8WebApp.Models.EmployeeSalaryInfo", b =>
                {
                    b.HasBaseType("Elev8WebApp.Models.Employee");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("numeric")
                        .HasColumnName("deductions");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric")
                        .HasColumnName("salary");

                    b.ToTable("employee_salaries");
                });

            modelBuilder.Entity("Elev8WebApp.Models.EmployeeSalaryInfo", b =>
                {
                    b.HasOne("Elev8WebApp.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Elev8WebApp.Models.EmployeeSalaryInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
